[package]
name        = "flix-time"
description = "A wrapper over Java's time library so it can be used by Flix."
version     = "0.19.0"
flix        = "0.75.0"
license     = "Apache-2.0"
authors     = ["Stephen Tetley <stephen.tetley@gmail.com>"]

[dependencies]
"github:stephentetley/charset-locale" = { version = "0.14.1", security = "unrestricted" }

